name = "clinc-ai-assistnant-project"
compatibility_date = "2026-03-01"

[build]
command = "npm --prefix frontend install && npm --prefix frontend run build"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
